In [2]:
#1
import numpy as np
a = np.random.rand(3, 5)
b = np.random.rand(3,5)
print(a)
print(b)

[[0.2085503  0.7658756  0.19600697 0.15724727 0.38095814]
 [0.34157705 0.59223621 0.14258992 0.20780508 0.82013549]
 [0.47652818 0.59738499 0.18313954 0.65682292 0.49415583]]
[[0.09099157 0.64638874 0.88293428 0.60924562 0.60424156]
 [0.44613899 0.34612362 0.62323909 0.20867502 0.41683002]
 [0.51034543 0.26378919 0.53761896 0.95340199 0.66620393]]


In [7]:
#2
c = np.arange(100)
print(c)

d = np.zeros((3,3))
print(d)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [10]:
#3
e = [[1,2,3],[4,5,6],[7,8,9]]

e = np.array(e)
print(e)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
#4
f = np.ones((5, 5))
print(f)
g = np.eye(5)
print(g)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [22]:
h = np.reshape(c, (10,10))
print(h)

c1 = h.flatten()
print(c1)

if(np.array_equal(c, c1)):
    print('Yes')
else:
    print('No')

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
Yes


In [28]:
A = np.random.rand(2,10,5)
A1 = A.T.reshape(5,2,10)
print(A1)
print(A1.shape)

[[[0.94596523 0.01160936 0.08534832 0.04545073 0.34038306 0.8748501
   0.9999403  0.66001056 0.58460513 0.4630396 ]
  [0.14634879 0.85282815 0.46178476 0.64965571 0.38326212 0.62880564
   0.46913369 0.4487246  0.60330444 0.29221394]]

 [[0.81086836 0.88711997 0.08339931 0.04114832 0.53914239 0.90951032
   0.3617074  0.08176565 0.92381357 0.04610811]
  [0.60819261 0.83587564 0.04547663 0.86273477 0.13894153 0.74958808
   0.93123851 0.45212332 0.86714385 0.81883338]]

 [[0.50050194 0.38528172 0.76731493 0.29409554 0.94110389 0.54576468
   0.33655447 0.07394583 0.40018545 0.43140748]
  [0.40561166 0.76220611 0.89353762 0.95532387 0.11184046 0.16573849
   0.80089317 0.22267482 0.16422822 0.54958261]]

 [[0.87207166 0.9149905  0.95724052 0.41476296 0.61920189 0.50561317
   0.52875238 0.46489987 0.33877819 0.31423387]
  [0.5830861  0.34984557 0.62595406 0.98097539 0.68679857 0.26690403
   0.38480278 0.37056431 0.43286173 0.37976155]]

 [[0.60877902 0.27957431 0.63954051 0.5627319  0.51719746

In [63]:
M = np.random.rand(10, 5)
print(M)
a
minCol = np.amin(M, axis = 0)
print(minCol)

minColInd = np.argmin(M, axis = 0)
print(minColInd)

#b
maxCol = np.amax(M, axis = 0)
print(maxCol)

maxColInd = np.argmax(M, axis = 0)
print(maxColInd)

#c
minRow = np.amin(M, axis = 1)
print(minRow)

minRowInd = np.argmin(M, axis = 1)
print(minRowInd)

d
maxRow = np.amax(M, axis = 1)
print(maxRow)

maxRowInd = np.argmax(M, axis = 1)
print(maxRowInd)

e
minMat = np.min(M)
print(minMat)

f
maxMat = np.max(M)
print(maxMat)



[[0.30712278 0.68689323 0.9611318  0.69829364 0.62298073]
 [0.14079542 0.1978698  0.49294049 0.39336435 0.45011316]
 [0.51069626 0.48680093 0.74068892 0.52245256 0.88054264]
 [0.19777307 0.14704625 0.91387139 0.72704899 0.65840979]
 [0.32978051 0.3571468  0.57459425 0.00368375 0.77593803]
 [0.27078595 0.34902322 0.01057715 0.12117865 0.84031133]
 [0.01635835 0.45273863 0.80819523 0.43072266 0.04916843]
 [0.69043822 0.9135056  0.77613167 0.59850582 0.66105635]
 [0.85347871 0.26412305 0.24864388 0.37076542 0.36996106]
 [0.08128999 0.46302693 0.74051958 0.91045316 0.68370834]]
[0.01635835 0.14704625 0.01057715 0.00368375 0.04916843]
[6 3 5 4 6]
[0.85347871 0.9135056  0.9611318  0.91045316 0.88054264]
[8 7 0 9 2]
[0.30712278 0.14079542 0.48680093 0.14704625 0.00368375 0.01057715
 0.01635835 0.59850582 0.24864388 0.08128999]
[0 0 1 1 3 2 0 3 2 0]
[0.9611318  0.49294049 0.88054264 0.91387139 0.77593803 0.84031133
 0.80819523 0.9135056  0.85347871 0.91045316]
[2 2 4 2 4 4 2 1 0 3]
0.003683747

In [64]:
#a
print(M)
meanCol = np.mean(M, axis = 0)
print(meanCol)

#b
meanRow = np.mean(M, axis = 1)
print(meanRow)

#c
stdCol = np.std(M, axis = 0)
print(stdCol)

#d
stdRow = np.std(M, axis = 1)
print(stdRow)

#e
meanMat = np.mean(M)
print(meanMat)

#f
stdMat = np.std(M)
print(stdMat)



[[0.30712278 0.68689323 0.9611318  0.69829364 0.62298073]
 [0.14079542 0.1978698  0.49294049 0.39336435 0.45011316]
 [0.51069626 0.48680093 0.74068892 0.52245256 0.88054264]
 [0.19777307 0.14704625 0.91387139 0.72704899 0.65840979]
 [0.32978051 0.3571468  0.57459425 0.00368375 0.77593803]
 [0.27078595 0.34902322 0.01057715 0.12117865 0.84031133]
 [0.01635835 0.45273863 0.80819523 0.43072266 0.04916843]
 [0.69043822 0.9135056  0.77613167 0.59850582 0.66105635]
 [0.85347871 0.26412305 0.24864388 0.37076542 0.36996106]
 [0.08128999 0.46302693 0.74051958 0.91045316 0.68370834]]
[0.33985193 0.43181744 0.62672944 0.4776469  0.59921898]
[0.65528444 0.33501664 0.62823626 0.5288299  0.40822867 0.31837526
 0.35143666 0.72792753 0.42139442 0.5757996 ]
[0.25557113 0.21860928 0.2861243  0.26215679 0.2368282 ]
[0.20911795 0.14008765 0.15576515 0.3032148  0.25896245 0.28609351
 0.29285502 0.10898628 0.22202817 0.28566673]
0.49505293875916195
0.27435955733694106


In [87]:
Y = np.random.rand(10,10)
print(Y)

#a
detMat = np.linalg.det(Y)
print(detMat)

#b
rankMat = np.linalg.matrix_rank(Y)
print(rankMat)

#c
diagMat = np.diagonal(Y)
print(diagMat)

#d
traceMat = np.trace(Y)
print(traceMat)

#e
eigValMat = np.linalg.eigvals(Y)
print(eigValMat)

#f
svdMat = np.linalg.svd(Y)
print(svdMat)

#g
if(np.linalg.det(Y) != 0):
    invMat = np.linalg.inv(Y)
    print('Exists')
    print(invMat)
else:
    print('Not Exists')
    print(np.linalg.pinv(Y))
    
#h
mulMat = np.multiply(Y, np.linalg.inv(Y) if np.linalg.det(Y) != 0 else np.linalg.pinv(Y))
print(mulMat)
    


[[0.84593568 0.08056124 0.02631064 0.09700071 0.31577907 0.77079798
  0.67832513 0.28491779 0.10749156 0.11912253]
 [0.3526786  0.9585615  0.95408898 0.13935778 0.50767988 0.65597754
  0.29741769 0.42075797 0.87811191 0.78077535]
 [0.43007133 0.68536721 0.14940967 0.97451262 0.51382794 0.01108468
  0.76709211 0.67545098 0.14149286 0.47909121]
 [0.03394679 0.92078416 0.34119393 0.56122593 0.52349355 0.46925056
  0.05205725 0.46258785 0.66548938 0.2541517 ]
 [0.956413   0.65850229 0.79167005 0.7499114  0.21611382 0.92019205
  0.28028    0.73300875 0.29698702 0.60644935]
 [0.44216859 0.60449398 0.41141704 0.72837683 0.49715906 0.32671778
  0.16509117 0.10311631 0.66044186 0.57035753]
 [0.14240513 0.61267294 0.14538574 0.24380879 0.56060919 0.14457975
  0.40360741 0.15921844 0.17496596 0.42903765]
 [0.81367771 0.58233523 0.94501779 0.93898933 0.77138882 0.51500593
  0.50690441 0.36955395 0.04221553 0.61859072]
 [0.36335581 0.86452644 0.04426169 0.47546172 0.43446609 0.10666486
  0.89021644